### ISSUE TITLE
Doesn't recognize department vs role

### ISSUE THREAD

**Issue by ravenx99** [akerl/hellolinodians#7]
"Congrats to Carl Cravens on their new job as an Operations at @linode,"

(Though one might argue this is a "bug" in the employees page, listing system administrators by their department when everyone else is listed by title.)

**Comment by akerl** [comment]
Yea, not much I can do here, since my only source of title info is the page.

One could argue that as far as Linode is concerned, your job is "Ops" and not "SysAdmin", but the ops vs devops vs sysadmin vs SRE vs whatever debate is almost as bad as vim vs emacs.

If anything, I might special-case "Operations" so that it says "new job on Operations" rather than the current hideous "new job as an Operations".

Where do I open an issue to get more accurate job titles, or at least have them standardized as singular nouns :)

**Comment by ravenx99** [comment]
The problem with saying my job is "Ops" means my title is "Operator" and I'm about 20 years past "operator" level.  (To me, "operators" change tapes, follow procedure manuals and call my team when something doesn't go according to the manual.)

Where to open an issue is my question at this point.  I think it's likely the work of the individual making updates rather than HR.

I figured you'd want a special-case in the meantime.

**Comment by akerl** [comment]
What an "Operator" is and whether the title reflects your job is a case you'd have to make internally :)

As an external 3rd party, special casing quickly becomes gnarly, since I'm no longer reflecting the information provided by the authoritative source (linode.com)

If linode.com/employees or another parse-able source provided more descriptive titles/roles, I'd be happy to include them in the library and feed.
